### ISSUE TITLE
[BUG]: Lobby list ist is not getting updated for the user leaving a lobby

### ISSUE THREAD

**Issue by Til7701** [schlunzis/Kurtama#134]
### What happened?

The message is not sent to the user.

### Steps to reproduce

1. Start one client
2. log in
3. create a lobby
4. leave the lobby

### Expected behaviour

The lobby list should be empty.

### Actual behaviour

The lobby list is not empty

### Further Information

nothing

### Version

1.0-SNAPSHOT

### What OS are you using

Windows

**Comment by JayPi4c** [comment]
I can't confirm the bug. I just tried it on the latest develop version and the lobbylist is being updated and cleaned. In fact, I checked the code and it seems to me, that everything is in order to correctly work. 
When the server receives a `LeaveLobbyRequest` the following method is triggered:
https://github.com/schlunzis/Kurtama/blob/b3673c3f86d92320859ed67f87ea86f7b5552cf0/server/src/main/java/org/schlunzis/kurtama/server/lobby/LobbyService.java#L64-L81
The user is removed and informed. And so are the other members of the lobby. The relevant part is in line 72. There is a call to `updateLobbyListInfo(...)`. A closer look to this method shows us, that every user, including the one leaving the lobby is getting the information about the updated lobby. This includes a reduced lobby member size or a removed lobby, if there is no member left.
https://github.com/schlunzis/Kurtama/blob/b3673c3f86d92320859ed67f87ea86f7b5552cf0/server/src/main/java/org/schlunzis/kurtama/server/lobby/LobbyService.java#L87-L90
In the client then, the `SessionService` is picking up the `LobbyListInfoMessage` and updates the list as needed:
https://github.com/schlunzis/Kurtama/blob/b3673c3f86d92320859ed67f87ea86f7b5552cf0/client/src/main/java/org/schlunzis/kurtama/client/service/impl/SessionService.java#L40-L45

**Comment by Til7701** [comment]
Might be a race condition. Try to leave the lobby as soon a possible after creating it. It works sometimes, but not all the time. I got this log output in the client, when die bug occurs:
```
12:30:14.598 [JavaFX Application Thread] INFO  47771 o.s.k.c.n.i.NettyClient(NettyClient.java:85): Sending message {"discriminator":"CreateLobbyRequest","name":"df"}
12:30:14.604 [nioEventLoopGroup-2-1] INFO  47771 o.s.k.c.n.i.ClientHandler(ClientHandler.java:25): Message from Server: {"discriminator":"LobbyCreatedSuccessfullyResponse","lobby":{"discriminator":"LobbyDTO","id":"547507d4-36be-4fe5-98b2-b74193edd108","name":"df","users":[{"discriminator":"UserDTO","id":"a86f771d-e5ee-48b9-8ec0-1a0f406235dc","username":"test1"}],"chatID":"319e63a9-2b0a-4148-9a81-7e1ca37ff7df"}}
12:30:14.606 [JavaFX Application Thread] DEBUG 47771 n.r.f.c.FxWeaver(FxWeaver.java:391): Loading FXML resource at file:/home/tilman/IdeaProjects/Kurtama/target/classes/org/schlunzis/kurtama/client/fx/controller/lobby.fxml
12:30:14.606 [nioEventLoopGroup-2-1] INFO  47771 o.s.k.c.n.i.ClientHandler(ClientHandler.java:25): Message from Server: {"discriminator":"LobbyListInfoMessage","lobbies":[{"lobbyID":"547507d4-36be-4fe5-98b2-b74193edd108","lobbyName":"df","users":1}]}
12:30:16.244 [JavaFX Application Thread] INFO  47771 o.s.k.c.n.i.NettyClient(NettyClient.java:85): Sending message {"discriminator":"LeaveLobbyRequest","lobbyID":"547507d4-36be-4fe5-98b2-b74193edd108"}
12:30:16.252 [nioEventLoopGroup-2-1] INFO  47771 o.s.k.c.n.i.ClientHandler(ClientHandler.java:25): Message from Server: {"discriminator":"LeaveLobbySuccessfullyResponse"}{"discriminator":"LobbyListInfoMessage","lobbies":[]}
12:30:16.253 [JavaFX Application Thread] DEBUG 47771 n.r.f.c.FxWeaver(FxWeaver.java:391): Loading FXML resource at file:/home/tilman/IdeaProjects/Kurtama/target/classes/org/schlunzis/kurtama/client/fx/controller/main.fxml
```

As you can see, the client does not get the new LobbyListInfoMessage.

**Comment by Til7701** [comment]
This is the server log:

```
12:30:16.246 [nioEventLoopGroup-3-2] INFO  47071 o.s.k.s.n.n.ServerHandler(ServerHandler.java:52): Message received: {"discriminator":"LeaveLobbyRequest","lobbyID":"547507d4-36be-4fe5-98b2-b74193edd108"}
12:30:16.247 [nioEventLoopGroup-3-2] INFO  47071 o.s.k.s.n.n.ServerHandler(ServerHandler.java:54): converted to LeaveLobbyRequest[lobbyID=547507d4-36be-4fe5-98b2-b74193edd108]
12:30:16.247 [nioEventLoopGroup-3-2] INFO  47071 o.s.k.s.n.ClientMessageDispatcher(ClientMessageDispatcher.java:27): going to dispatch message LeaveLobbyRequest[lobbyID=547507d4-36be-4fe5-98b2-b74193edd108]
12:30:16.247 [nioEventLoopGroup-3-2] INFO  47071 o.s.k.s.n.ClientMessageDispatcher(ClientMessageDispatcher.java:36): Received authenticated ClientMessage
12:30:16.248 [] INFO  47071 o.s.k.s.l.LobbyManagement(LobbyManagement.java:51): User a86f771d-e5ee-48b9-8ec0-1a0f406235dc left lobby with id: 547507d4-36be-4fe5-98b2-b74193edd108
12:30:16.249 [] INFO  47071 o.s.k.s.l.LobbyManagement(LobbyManagement.java:55): Lobby 547507d4-36be-4fe5-98b2-b74193edd108 was empty and was removed.
12:30:16.249 [] ERROR 47071 o.s.k.s.l.LobbyService(LobbyService.java:98): Failed to inform users in lobby. Lobby not found. 
org.schlunzis.kurtama.server.lobby.exception.LobbyNotFoundException: null
	at org.schlunzis.kurtama.server.lobby.LobbyManagement.getLobby(LobbyManagement.java:67) ~[classes/:?]
	at org.schlunzis.kurtama.server.lobby.LobbyService.informUsersInLobby(LobbyService.java:94) ~[classes/:?]
	at org.schlunzis.kurtama.server.lobby.LobbyService.onLeaveLobbyRequest(LobbyService.java:71) ~[classes/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:365) ~[spring-context-6.1.2.jar:6.1.2]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:237) ~[spring-context-6.1.2.jar:6.1.2]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:168) ~[spring-context-6.1.2.jar:6.1.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178) ~[spring-context-6.1.2.jar:6.1.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171) ~[spring-context-6.1.2.jar:6.1.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.lambda$multicastEvent$0(SimpleApplicationEventMulticaster.java:146) ~[spring-context-6.1.2.jar:6.1.2]
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314) ~[?:?]
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:311) ~[?:?]
```

**Comment by JayPi4c** [comment]
Actually, the server does almost everything as intendent.
Looking at the client logs, there is something dubios:
`12:30:16.252 [nioEventLoopGroup-2-1] INFO  47771 o.s.k.c.n.i.ClientHandler(ClientHandler.java:25): Message from Server: {"discriminator":"LeaveLobbySuccessfullyResponse"}{"discriminator":"LobbyListInfoMessage","lobbies":[]}` 
Especially the received message is very interesting:
`{"discriminator":"LeaveLobbySuccessfullyResponse"}{"discriminator":"LobbyListInfoMessage","lobbies":[]}`
For some reason, I don't yet understand, the `LobbyListInfoMessage` and the `LeaveLobbySuccessfullyResponse` are merged to one string and send together. It's actually really interessting, that the software is able to parse this to a `LeaveLobbySuccessfullyResponse` without any problem. But the `LobbyListInfoMessage` seems to be lost in this process. That's why the list is not updated on the client.

**Comment by JayPi4c** [comment]
My current guess is, that there is some synchronisation issue with this method:
https://github.com/schlunzis/Kurtama/blob/b3673c3f86d92320859ed67f87ea86f7b5552cf0/server/src/main/java/org/schlunzis/kurtama/server/net/netty/ServerHandler.java#L89-L98
I don't know how, but I think, the second message is in the write process while first message has not been flushed yet. This results in both messages being written to the channel and the flush will send them together. 
But I fail to understand where the processing of the messages started to be asynchronous. Afaik the message processing is never separeted into individual threads.

**Comment by Til7701** [comment]
This seems to be how TCP works:
https://stackoverflow.com/questions/55688912/different-response-messages-are-merging-while-read-from-netty-server
https://stackoverflow.com/questions/35652207/netty-concatenates-messages-that-arrive-simultaneously

**Comment by JayPi4c** [comment]
Very interesting indeed. Good to know that we did not make a mistake in the usage of our technology stack. Knowing these stackoverflow threads, I think prepending the length of the packets we are sending might just be the solution to our problem.
