### ISSUE TITLE
Welcome chat message not printed consistently 

### ISSUE THREAD

**Issue by JayPi4c** [schlunzis/Kurtama#206]
### What happened?

When logging the chat does not always show the welcome message in the chat.

### Steps to reproduce

1. Login
2. Be unlucky and don't get the Welcome message 

### Expected behaviour

Get the welcome message constantly 

### Actual behaviour

Getting the message by chance 

### Further Information

I guess it's something about the timing of the welcome chat message and the time it needs in the client to build the main menu scene. Or the messages are merged together and the chat message is corrupted and is therefore not correctly shown.

### Which version of our software are you running?

Latest develop branch

### Which OS are you using?

Ubuntu

### How did you download the software?

built from source

**Comment by Til7701** [comment]
Due to the asynchronous nature of out event publisher, there is a race condition. It can be solved by adding a sleep in between publish and close in `ClientMessageContext.closeWithReRequest()`. That's obviously not a good solution. We either have to introduce some kind of lock or make sure that specific publish is run in the same thread.

**Comment by JayPi4c** [comment]
When considering to fix this with a lock, maybe we can have a look at https://projectlombok.org/features/Locked
